const { Schema, model } = require("mongoose")

module.exports = model("User", new Schema({
    Guild: String,
    User: String,
    Points: Number,
    Messages: Number,
    AFKStatus: Boolean,
    AFKReason: String,
    AFKNickname: String,
    AFKStart: String,
    AFKReason: String,
    VoiceStart: Number,
    VoiceTime: Number,
    InviterID: String,
    Code: String,
    Invites: Number,
    InvitesJoins: Number,
    InvitesLeft: Number,
    InvitesRejoins: Number,
    InvitedList: Array,
    InvitedTag: Array,
    Level: Number,
    XP: Number,
    Checkpoint: Number,
    MarriagePartner: String,
    MarriageStatus: Boolean,
    MarriedList: Array,
    MarriedTag: Array,
    Reputations: Number,
    LastReputation: String,
    ReputationCD: String,
}))